### PR TITLE
Create models and controllers for lessons (rebased against `main` and fixed up)

### PR DESCRIPTION
**Pull request by floehopper**
We created this PR as follows:
1. Creating a new branch based on the latest `main`.
2. Cherry-picking the commits from #241 that were not included in [this squash merge commit](https://github.com/RaspberryPiFoundation/editor-api/commit/c93169b9ceddfa9958faf98f25be7e904e99d2a3).
3. Resolving a number of conflicts, particularly a bunch relating to a user's roles and organisations caused by some changes in #242 which added a new "editor-admin" role.
4. Fixing a bug we noticed in `User.temporarily_add_organisations_until_the_profile_app_is_updated`.
5. Adding a bit of missing test coverage.

TODO:
* [x] Do some manual testing of the `editor-ui` app and/or the `editor-standalone` app against the code in this branch. In particular, it would be worth testing some operations on a user (e.g. logging in) and operations on projects (e.g. creating & updating).
* [ ] ~Although I have already reviewed these commits as part of my original review of #241, it might be worth someone else reviewing the (much smaller number of) commits in this PR.~
* [x] Add an issue for adding proper support for non-organisation-specific roles if we think this is likely to be needed
* [ ] ~We might want to replace the original `issues/239-Create_models_and_controllers_for_lessons` branch with this `issues/239-Create_models_and_controllers_for_lessons-rebased-against-main-and-fixed-up` branch to keep GitHub projects happy before we merge these changes, but I'm not sure it's essential.~
* [x] I'd recommend we rebase this branch against `main` just before merging, force-push if necessary, and then merge with a merge commit (but *not* squashing) in order to preserve the original individual commits to make it easier to see what's happened.

/cc @sra405 @tuzz @chrislo @chrisroos

### CODE REVIEW

**Comment by floehopper** [comment]
> * [ ] Do some manual testing of the `editor-ui` app and/or the `editor-standalone` app against the code in this branch. In particular, it would be worth testing some operations on a user (e.g. logging in) and operations on projects (e.g. creating & updating).

I've had a go at doing this locally and this is what led me to finding and fixing the problem described in https://github.com/RaspberryPiFoundation/editor-api/pull/258/commits/0148d94fcedf612df52e799add43b16d0379f566.

One I was concerned about was that logged-in users with *no roles* would still be able to do what they used to be able to do and that does indeed appear to be the case. And I've double-checked this by reading the code:

* Anyone can view projects not owner by a user or a school:

In `main`:
https://github.com/RaspberryPiFoundation/editor-api/blob/c0e104db9c1c1af0277efaed70fd4e8f444fbd26/app/models/ability.rb#L8-L9

In this branch:
https://github.com/RaspberryPiFoundation/editor-api/blob/0148d94fcedf612df52e799add43b16d0379f566/app/models/ability.rb#L8-L10

* Any authenticated user can create projects not owned by a school:

In `main`:
https://github.com/RaspberryPiFoundation/editor-api/blob/c0e104db9c1c1af0277efaed70fd4e8f444fbd26/app/models/ability.rb#L13-L14

In this branch:
https://github.com/RaspberryPiFoundation/editor-api/blob/0148d94fcedf612df52e799add43b16d0379f566/app/models/ability.rb#L17C7-L19

* Any authenticated user can manage their own projects:

In `main`:
https://github.com/RaspberryPiFoundation/editor-api/blob/c0e104db9c1c1af0277efaed70fd4e8f444fbd26/app/models/ability.rb#L13-L14

In this branch:
https://github.com/RaspberryPiFoundation/editor-api/blob/0148d94fcedf612df52e799add43b16d0379f566/app/models/ability.rb#L21C7-L23

I've also confirmed that after [this fix](https://github.com/RaspberryPiFoundation/editor-api/pull/258/commits/80e3c88a16374c19fc42c0de696f1143cfd8fe4e) I can login to the admin dashboard with a user that has the "editor-admin" role.

So I'm happy to tick this checkbox.

**Comment by floehopper** [comment]
> * [ ] Although I have already reviewed these commits as part of my original review of #241, it might be worth someone else reviewing the (much smaller number of) commits in this PR.

Given that both @chrislo & I looked at a lot of the commits during our efforts to rebase the branch and all the manual testing I've done. I'm no longer convinced this is worthwhile, so I'm happy to delete this checkbox item.

**Comment by floehopper** [comment]
> * [ ] Add an issue for adding proper support for non-organisation-specific roles if we think this is likely to be needed

I've created an issue in the "Ideas" section of the project: https://github.com/RaspberryPiFoundation/editor-ui/issues/984

I hope that makes sense. /cc @sra405

**Comment by floehopper** [comment]
> * [ ] We might want to replace the original `issues/239-Create_models_and_controllers_for_lessons` branch with this `issues/239-Create_models_and_controllers_for_lessons-rebased-against-main-and-fixed-up` branch to keep GitHub projects happy before we merge these changes, but I'm not sure it's essential.

I've discovered that it is possible to associate multiple PRs with an issue, so I don't think this step is necessary.

**Comment by floehopper** [comment]
> * [ ] I'd recommend we rebase this branch against `main` just before merging, force-push if necessary, and then merge with a merge commit (but *not* squashing) in order to preserve the original individual commits to make it easier to see what's happened.

The branch is still up-to-date against `main`, but I will double-check before merging.

**Comment by sra405** [comment]
> I've created an issue in the "Ideas" section of the project: [RaspberryPiFoundation/editor-ui#984](https://github.com/RaspberryPiFoundation/editor-ui/issues/984)
> 
> I hope that makes sense. /cc @sra405

Thanks @floehopper that makes sense to me 👍 thanks for adding the ticket, it's definitely one that needs mulling over

**Review by chrisroos — APPROVED** [review]
@chrislo and I have reviewed the last 6 commits and they look good to us :+1:

**Pull request merged**
